version: '3.9'

services:
  postgres: # the container host address is postgres
    image: postgres:14.2-alpine3.15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_management
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgres

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    networks:
      - postgres

volumes:
  postgresql_data:

networks:
  postgres:
