version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_management
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgres
#
#  api:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - "postgres"

volumes:
  postgresql_data:


networks:
  postgres:
