version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_management
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgres

  dbeaver:
    image: dbeaver/cloudbeaver:22.2.5
    ports:
      - "8081:8978"
    volumes:
      - workspace:/opt/cloudbeaver/workspace
    networks:
      - postgres

volumes:
  postgresql_data:
  workspace:

networks:
  postgres:
