version: '3.9'

services:
  mysql:
    image: 'bitnami/mysql:5.7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin@123
      - MYSQL_DATABASE=inventory_management
    ports:
      - "3306:3306"
    networks:
      - app-tier
    volumes:
      - mysql-persistence:/bitnami/mysql/data

volumes:
  mysql-persistence:

networks:
  app-tier:
