version: '3.9'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_management
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgresql_data:

networks:
  postgres: