spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

datasource-url: jdbc:mysql://localhost:3306/inventory_management
datasource-username: user
datasource-password: admin@123
datasource-driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-stacktrace: on_param

jwt:
  secret: WzYwLCAtMTE0LCAtMTI4LCAtMTIsIC0xMjgsIDExLCAtODgsIC0xMjAsIDEwNywgMzMsIDY0LCA1OSwgLTcsIDY5LCAxMCwgLTk4LCAtNzUsIDEyMywgMjIsIC0zNSwgNzcsIC0xMTYsIDExMywgOTgsIDExNSwgLTk5LCAtNjMsIC01MiwgMTExLCAtNzMsIC0xMTcsIDQzXQ==